name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Lint and Tests
      run: make test